---

name: Lint Code Base

on: [push, pull_request]

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: lint
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: true
